### ISSUE TITLE
CTD on f11 use

### ISSUE THREAD

**Issue by Raggtop666** [Qudix/QUI-SKSE#15] opened 2021-12-31 06:57 UTC
so i have tried you QUI-SKSE main and i cant get the F11 to work and as i was reading i saw the QUI AE build and as i used the F11 it CTD im using Vortex as my mod manger and i have all the Required mods installed is there somthing that i missed in the install if not then I'd say its a big bug my attempt was new game using ASLAL mod and using QAsmoke for testing and both CTD

**Comment by rrgraw** [comment] 2022-01-03 00:55
I think that is caused by using SSE Engine Fixes (SKSE64 plugin) at the some time as this mod.

**Comment by MBassoX** [comment] 2022-01-06 22:31
i have similar issue.. sometimes it works and suddenly i press f11 it ctd. it nedd to be updated

**Comment by tensei123** [comment] 2022-01-09 23:16
Same here, not working, CTD not happen to me just never open the mod.

**Comment by qudix** [comment] 2022-02-23 04:53
Closing as there is not enough info, like crash logs or crash dumps (etc).

**Closed as completed by qudix** 2022-02-23 04:53 UTC
