### ISSUE TITLE
CTD when trying to open this

### ISSUE THREAD

**Issue by zhongjiedong** [Qudix/QUI-SKSE#2] opened 2021-10-30 21:49 UTC
I had a spell out on right hand and shield on left. Attempting to open it caused a ctd. Crashlog attache
[Crash_2021_10_30_22-47-4.txt](https://github.com/Qudix/QUI-SKSE/files/7447650/Crash_2021_10_30_22-47-4.txt)
d

**Comment by qudix** [comment] 2021-10-30 22:39
Is the crash reproducible? Because I can't replicate the issue.

**Comment by zhongjiedong** [comment] 2021-10-30 23:26
Yes every time i press f11 it just crashes. Not sure how it worked the one time 🤔

**Comment by TwistedModding** [comment] 2021-10-31 03:33
I'm unable to replicate either.

**Comment by zhongjiedong** [comment] 2021-10-31 04:02
I wonder if it's because of the Dienes Tools https://www.nexusmods.com/skyrimspecialedition/mods/31187

**Comment by Stas-sudo** [comment] 2021-12-05 19:51
@zhongjiedong i don't use the mod you mentioned, but i'm getting the CTD's too.

**Comment by qudix** [comment] 2021-12-07 20:00
This should be fixed in the latest 0.2.2 release.

**Closed as completed by qudix** 2021-12-07 20:00 UTC
Labels: bug
